# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0-noble AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0-noble AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Fundo.Applications.WebApi/Fundo.Applications.WebApi.csproj", "Fundo.Applications.WebApi/"]
COPY ["Fundo.Applications.Domain/Fundo.Applications.Domain.csproj", "Fundo.Applications.Domain/"]
COPY ["Fundo.Applications.Application/Fundo.Applications.Application.csproj", "Fundo.Applications.Application/"]
COPY ["Fundo.Applications.Infrastructure/Fundo.Applications.Infrastructure.csproj", "Fundo.Applications.Infrastructure/"]
RUN dotnet restore "./Fundo.Applications.WebApi/Fundo.Applications.WebApi.csproj"
COPY . .
WORKDIR "/src/Fundo.Applications.WebApi"
RUN dotnet build "./Fundo.Applications.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Fundo.Applications.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Fundo.Applications.WebApi.dll"]