/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Fundo.Applications.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from '../client/axiosInstance';
/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
export type LoanDtoAmount = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
export type LoanDtoCurrentBalance = number | string;

export type LoanDtoId = null | string;

export interface LoanDto {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  amount?: LoanDtoAmount;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  currentBalance?: LoanDtoCurrentBalance;
  applicantName?: string;
  status?: LoanStatus;
  id?: LoanDtoId;
}

export type LoanStatus = typeof LoanStatus[keyof typeof LoanStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanStatus = {
  Active: 'Active',
  Paid: 'Paid',
} as const;

/**
 * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
 */
export type PaymentRequestAmount = number | string;

export interface PaymentRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  amount?: PaymentRequestAmount;
}

export const getFundoApplicationsWebApiV1 = () => {
const getLoans = (
    
 ) => {
      return axiosInstance<LoanDto[]>(
      {url: `/loans`, method: 'GET'
    },
      );
    }
  
const postLoans = (
    loanDto: LoanDto,
 ) => {
      return axiosInstance<LoanDto>(
      {url: `/loans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loanDto
    },
      );
    }
  
const getLoansId = (
    id: string,
 ) => {
      return axiosInstance<LoanDto>(
      {url: `/loans/${id}`, method: 'GET'
    },
      );
    }
  
const postLoansIdPayment = (
    id: string,
    paymentRequest: PaymentRequest,
 ) => {
      return axiosInstance<LoanDto>(
      {url: `/loans/${id}/payment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: paymentRequest
    },
      );
    }
  
return {getLoans,postLoans,getLoansId,postLoansIdPayment}};
export type GetLoansResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFundoApplicationsWebApiV1>['getLoans']>>>
export type PostLoansResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFundoApplicationsWebApiV1>['postLoans']>>>
export type GetLoansIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFundoApplicationsWebApiV1>['getLoansId']>>>
export type PostLoansIdPaymentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFundoApplicationsWebApiV1>['postLoansIdPayment']>>>
